---
input: # mandatory, all files in here are tab-delimited tabular data
  hla_map: "/pipeline/inputs/T1D67_mapping.tsv"
  dq_rank: "/pipeline/inputs/HLADQ_USAEuropean_Klitz.tsv"
  max_dq_calls: 2 # not implemented yet
scores: # mandatory
  interaction: "/pipeline/inputs/T1D67_interaction_scores.tsv"
  all_variants: "/pipeline/inputs/T1D67_plink_all_scores.tsv"
  hla_variants: "/pipeline/inputs/T1D67_plink_hla_scores.tsv" # optional, will automatically exclude HLA BETAs from final calculation if this key-value pair is removed
metrics: # optional, will not compute centiles, PPV or case probability if this key (and child key-value pairs) is removed
  centiles_file: "/pipeline/inputs/UKBB_T1D67_ROC.tsv"
  params_file: "/pipeline/inputs/UKBB_T1D67_Fit.tsv"
