# Base image
FROM rocker/r-ubuntu:22.04

# Maintainer and author
LABEL maintainer="Nathan Gaddis <ngaddis@rti.org>"

# Configure default locale, see https://github.com/rocker-org/rocker/issues/19
RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
    && locale-gen en_US.utf8 \
    && /usr/sbin/update-locale LANG=en_US.UTF-8
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8

#### Install general packages
RUN rm -Rf /var/lib/apt/lists/*
RUN apt-get update \
    && apt-get install -y \
        curl \
        awscli

#### Install plink1.9 ####
RUN apt-get install -y \
        curl \
        fonts-texgyre \
        libatlas-base-dev
RUN wget https://github.com/chrchang/plink-ng/archive/refs/tags/b15c19f.tar.gz \
    && tar -xvzf b15c19f.tar.gz \
    && mv plink-ng-b15c19f/ /plink_tmp/
COPY dependencies/plink_common.h /plink_tmp/1.9/plink_common.h
COPY dependencies/sse2neon.h /plink_tmp/1.9/sse2neon.h 
COPY dependencies/SFMT.h /plink_tmp/1.9/SFMT.h
RUN cd /plink_tmp/1.9/ \
    && ./plink_first_compile \
    && cp /plink_tmp/1.9/plink /opt/plink1.9 \
    && cd / \
    && rm -rf b15c19f.tar.gz plink_tmp

#### Install plink2 ####
ENV DEBIAN_FRONTEND noninteractive
RUN wget https://s3.amazonaws.com/plink2-assets/alpha6/plink2_linux_x86_64_20250129.zip \
    && unzip plink2_linux_x86_64_20250129.zip -d /plink_tmp \
    && cp /plink_tmp/plink2 /opt/ \
    && rm -rf plink2_linux_x86_64_20250129.zip plink_tmp
ENV PATH=pkg-config:$PATH:/opt/

#### Install eigensoft ####
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libgsl-dev \
        libopenblas-dev \
        liblapacke-dev \
    && wget https://github.com/DReichLab/EIG/archive/v7.2.1.tar.gz \
    && tar -xvzf v7.2.1.tar.gz \
    && cd EIG-7.2.1/src/ \
    && perl -i.bak -pe 's/# override LDLIBS \+= -llapacke/override LDLIBS += -llapacke/;' Makefile \
    && make clobber \
    && make install
ENV PATH=$PATH:/EIG-7.2.1/bin
RUN rm -Rf /var/lib/apt/lists/*

#### Install R libraries
RUN R -e "install.packages('scatterplot3d',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('optparse',dependencies=TRUE, repos='http://cran.rstudio.com/')"

#### Install python and python libraries
# Install python3 and pip
RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip3 install --upgrade pip
RUN pip3 install boto3

#### Install awscli
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install
RUN rm -rf awscliv2.zip
RUN rm -rf aws

# Add pipeline config files
RUN mkdir -p /pipeline/config
ADD config/ancestry_pipeline_entrypoint_bfile.json /pipeline/config/
ADD config/ancestry_pipeline_entrypoint_gvcf.json /pipeline/config/
ADD config/ancestry_tasks.json /pipeline/config/

#### Install custom scripts ####
# Add scripts
RUN mkdir -p /pipeline/scripts
ADD scripts/add_pop_ids_to_fam_files.pl /pipeline/scripts/
ADD scripts/assign_ancestry_mahalanobis.R /pipeline/scripts/
ADD scripts/assign_ids_to_dataset_bim.pl /pipeline/scripts/
ADD scripts/entrypoint.sh /pipeline/scripts/
ADD scripts/get_ancestry_assignment.pl /pipeline/scripts/
ADD scripts/get_ref_samples.pl /pipeline/scripts/
ADD scripts/get_ref_variants_from_dataset_gvcf.pl /pipeline/scripts/
ADD scripts/prepare_smartpca_input.pl /pipeline/scripts/
ADD scripts/process_smartpca_results.pl /pipeline/scripts/
ADD scripts/run_pipeline.py /pipeline/scripts/

# Change permissions
RUN chmod 755 /pipeline/scripts/add_pop_ids_to_fam_files.pl
RUN chmod 755 /pipeline/scripts/assign_ancestry_mahalanobis.R
RUN chmod 755 /pipeline/scripts/assign_ids_to_dataset_bim.pl
RUN chmod 755 /pipeline/scripts/entrypoint.sh
RUN chmod 755 /pipeline/scripts/get_ancestry_assignment.pl
RUN chmod 755 /pipeline/scripts/get_ref_samples.pl
RUN chmod 755 /pipeline/scripts/get_ref_variants_from_dataset_gvcf.pl
RUN chmod 755 /pipeline/scripts/prepare_smartpca_input.pl
RUN chmod 755 /pipeline/scripts/process_smartpca_results.pl
RUN chmod 755 /pipeline/scripts/run_pipeline.py

WORKDIR /data

ENTRYPOINT [ "/pipeline/scripts/entrypoint.sh" ]

