name: 'Build and Publish Docker'
author: 'Chris Ball'
branding:
  icon: 'code'
  color: 'green'
description: 'Builds the specified Dockerfile and pushes the image to Docker Hub.'
inputs:
  username:
    description: 'The login username for the registry'
    required: true
  password:
    description: 'The login password for the registry'
    required: true
  organization:
    description: 'The organization to push the image to'
    required: true
outputs:
  tag:
    description: 'Is the tag, which was pushed'
  digest:
    description: 'Is the digest of the image, which was pushed'
runs:
  using: 'docker'
  image: 'Dockerfile'
