name: 'Build and Publish Docker'
author: 'Jesse Marks'
branding:
  icon: 'code'
  color: 'green'
description: 'Builds the specified Dockerfile and pushes the image to Docker Hub.'
inputs:
  changed_files:
    description: 'The files changed in the triggering commit.'
    required: true
  username:
    description: 'The login username for the registry'
    required: true
  password:
    description: 'The login password for the registry'
    required: true
  organization:
    description: 'The organization to push the image to'
    required: true
outputs:
  tag:
    description: 'Is the tag that was pushed'
  digest:
    description: 'Is the digest of the pushed image'
runs:
  using: 'docker'
  image: 'Dockerfile'
