# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-imputationserver
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - r=4.1.0
  - r-rmarkdown=2.16
  - r-ggplot2=3.3.6
  - r-htmltools=0.5.3
  - r-dplyr=1.1.0
  - r-dt=0.24
  - r-tidyr=1.2.1  
  - r-rmdformats=1.0.4
  - pandoc=2.19.2
  - cairo=1.16.0
  - xorg-libxt=1.2.1
  - fonts-anaconda=1
  - openjdk=17.0.3
 # - r-rcolorbrewer=1.1_3
 # - bioconductor-geneplotter=1.60.0
 # - r-kernsmooth #use this?
  - csvtk=0.25.0
  - unzip=6.0
  - P7Zip=15.09
  - bcftools=1.20