# Bulk RNA-seq QC pipeline: load inputs, compute sample metrics, generate plots,
# apply QC thresholds, and write HTML/Markdown summaries.
pacman::p_load(
	logr, dplyr, tibble, stringr, DESeq2, tximport, patchwork, ggplot2,
	SummarizedExperiment
)

source("bulk_rnaseq_qc_functions.R")

args <- commandArgs(TRUE)

usage <- paste(
	"Usage: Rscript bulk_rnaseq_quality_control.R",
	"--multiqc_dir <path>",
	"--txi_rds <path>",
	"--pheno_tsv <path>",
	"--annotation_gtf <path>",
	"--sample_id_col <colname>",
	"--run_name <name>",
	"[--output_dir <path>]",
	"[--rin_col <colname>]",
	"[--sex_col <colname>]",
	"[--group_vars <comma-separated-colnames>]"
)

if (length(args) < 12) {
	stop(usage)
}

# Validate required CLI flags before any file or object loading.
flag_args <- parse_flag_args(args)
required_flags <- c("multiqc_dir", "txi_rds", "pheno_tsv", "annotation_gtf", "sample_id_col", "run_name")
missing_flags <- required_flags[!required_flags %in% names(flag_args)]
if (length(missing_flags) > 0) {
	stop(paste0("Missing required flags: ", paste(missing_flags, collapse = ", "), "\n", usage))
}

# Directory generated by MultiQC parser inputs.
multiqc_dir <- flag_args$multiqc_dir
# tximport object (.rds) containing counts/abundance/length.
txi_rds <- flag_args$txi_rds
# Phenotype table.
pheno_tsv <- flag_args$pheno_tsv
# GTF annotation file used for mito/ribo/chrY-derived metrics.
annotation_gtf <- flag_args$annotation_gtf
# Run identifier used in outputs and logs.
run_name <- flag_args$run_name
# Optional parent output directory. Defaults to outputs.
output_dir <- if ("output_dir" %in% names(flag_args)) {
	flag_args$output_dir
} else {
	"outputs"
}
# Required phenotype ID column.
sample_id_col <- flag_args$sample_id_col
# Optional RIN column name in phenotype table.
rin_col <- if ("rin_col" %in% names(flag_args)) flag_args$rin_col else "RIN"
# Optional sex column name for sex-stratified QC metrics.
sex_col <- if ("sex_col" %in% names(flag_args)) flag_args$sex_col else "Sex"
# Optional comma-separated list of phenotype columns for PCA grouping.
group_vars_arg <- if ("group_vars" %in% names(flag_args)) {
	flag_args$group_vars
} else {
	NULL
}
group_vars <- if (is.null(group_vars_arg)) {
	character(0)
} else {
	trimws(strsplit(group_vars_arg, ",", fixed = TRUE)[[1]])
}
group_vars <- group_vars[nzchar(group_vars)]

# Create a run-scoped output tree and central log file.
out_dir <- file.path(output_dir, paste0(run_name, "_quality_control"))
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
plot_dir <- file.path(out_dir, "plots")
dir.create(plot_dir, recursive = TRUE, showWarnings = FALSE)
table_dir <- file.path(out_dir, "tables")
dir.create(table_dir, recursive = TRUE, showWarnings = FALSE)

log_file <- file.path(out_dir, "bulk_rnaseq_qc.log")
lf <- logr::log_open(
	log_file, logdir = FALSE, show_notes = FALSE, traceback = FALSE
)
on.exit(logr::log_close())

logr::sep("Input parameters")
logr::log_print(paste("MultiQC dir:", multiqc_dir), console = FALSE)
logr::log_print(paste("txi RDS:", txi_rds), console = FALSE)
logr::log_print(paste("Phenotype TSV:", pheno_tsv), console = FALSE)
logr::log_print(paste("Annotation GTF:", annotation_gtf), console = FALSE)
logr::log_print(paste("Run name:", run_name), console = FALSE)
logr::log_print(paste("Output directory:", out_dir), console = FALSE)
logr::log_print(paste("Sample ID column:", sample_id_col), console = FALSE)
logr::log_print(paste("RIN column:", rin_col), console = FALSE)
logr::log_print(paste("Sex column:", sex_col), console = FALSE)
if (length(group_vars) > 0) {
	logr::log_print(
		paste("PCA group vars:", paste(group_vars, collapse = ", ")),
		console = FALSE
	)
} else {
	logr::log_print("PCA group vars: not provided; PCA plotting will be skipped.", console = FALSE)
}

required_paths <- c(multiqc_dir, txi_rds, pheno_tsv, annotation_gtf)
missing_paths <- required_paths[!file.exists(required_paths)]
if (length(missing_paths) > 0) {
	stop(
		paste0(
			"Missing required input path(s): ",
			paste(missing_paths, collapse = ", ")
		)
	)
}

logr::sep("Load QC and expression inputs")

# Load MultiQC-derived data and normalize expected nested structures.
qc_data <- load_paired_end_qc_data(data_dir = multiqc_dir)
logr::log_print("Loaded multiqc-derived qc_data object.", console = FALSE)

for (nm in c(
	"seq_duplication", "phred_bp", "phred_seq", "adapter_content",
	"gc_content", "fastqc"
)) {
	if (nm %in% names(qc_data)) {
		qc_data[[nm]] <- split_by_trim_status(qc_data[[nm]])
	}
}

fastqc_pre_subset <- if (
	"fastqc" %in% names(qc_data) &&
	is.list(qc_data$fastqc)
) {
	qc_data$fastqc
} else {
	NULL
}

txi <- readRDS(txi_rds)
if (!is.list(txi) || !"counts" %in% names(txi)) {
	stop("Input txi_rds must be an RDS containing a tximport-like list with counts.")
}

pheno_data <- read.table(pheno_tsv, sep = "\t", header = TRUE, check.names = FALSE)

# Optionally map a custom RIN column name to canonical RIN for downstream calls.
if (rin_col != "RIN" && rin_col %in% colnames(pheno_data)) {
	if ("RIN" %in% colnames(pheno_data)) {
		stop(
			paste0(
				"Both custom RIN column '", rin_col,
				"' and 'RIN' exist in phenotype table; refusing to overwrite existing 'RIN'."
			)
		)
	}
	colnames(pheno_data)[colnames(pheno_data) == rin_col] <- "RIN"
	group_vars[group_vars == rin_col] <- "RIN"
	rin_col <- "RIN"
}

# Enforce unique non-empty sample IDs before matching to tximport columns.
if (!sample_id_col %in% colnames(pheno_data)) {
	stop(
		paste0(
			"Sample ID column '", sample_id_col, "' not found in phenotype table."
		)
	)
}

sample_id_values <- as.character(pheno_data[[sample_id_col]])
if (any(is.na(sample_id_values) | sample_id_values == "")) {
	stop("Sample ID column contains missing or empty values.")
}
if (any(duplicated(sample_id_values))) {
	dup_vals <- unique(sample_id_values[duplicated(sample_id_values)])
	stop(
		paste0(
			"Sample ID column contains duplicate values; cannot set unique rownames. Duplicates include: ",
			paste(head(dup_vals, 10), collapse = ", ")
		)
	)
}
rownames(pheno_data) <- sample_id_values

shared_ids <- intersect(colnames(txi$counts), rownames(pheno_data))
if (length(shared_ids) == 0) {
	stop("No overlapping sample IDs between txi counts columns and phenotype rownames.")
}

txi <- subset_txi(txi = txi, ids = shared_ids, dimension = 2)
pheno_data <- pheno_data[shared_ids, , drop = FALSE]

dds <- DESeq2::DESeqDataSetFromTximport(txi, colData = pheno_data, design = ~1)
dds <- DESeq2::estimateSizeFactors(dds)
dds_vst <- DESeq2::vst(dds, blind = TRUE)
normalized_counts <- DESeq2::counts(dds, normalized = TRUE)

qc_ids <- rownames(pheno_data)

if (
	"fastqc" %in% names(qc_data) &&
	is.list(qc_data$fastqc) &&
	"trimmed_r1" %in% names(qc_data$fastqc)
) {
	pre_fastqc_ids <- extract_fastq_id(rownames(qc_data$fastqc$trimmed_r1))
	logr::log_print(
		paste("Phenotype ID examples:", paste(head(qc_ids, 6), collapse = ", ")),
		console = FALSE
	)
	logr::log_print(
		paste(
			"FastQC ID examples:",
			paste(head(pre_fastqc_ids, 6), collapse = ", ")
		),
		console = FALSE
	)
	logr::log_print(
		paste(
			"FastQC trimmed R1 overlap with phenotype IDs before subsetting:",
			length(intersect(pre_fastqc_ids, qc_ids))
		),
		console = FALSE
	)
	logr::log_print(
		paste(
			"FastQC overlap after normalized ID mapping:",
			length(intersect(normalize_sample_id(pre_fastqc_ids), normalize_sample_id(qc_ids)))
		),
		console = FALSE
	)
	logr::log_print(
		paste(
			"FastQC overlap after compact ID mapping:",
			length(intersect(normalize_sample_id_compact(pre_fastqc_ids), normalize_sample_id_compact(qc_ids)))
		),
		console = FALSE
	)
}

for (nm in names(qc_data)) {
	qc_data[[nm]] <- subset_qc_object(qc_data[[nm]], ids = qc_ids)
}

trimmed_r1_n <- if (
	"fastqc" %in% names(qc_data) &&
	"trimmed_r1" %in% names(qc_data$fastqc)
) {
	nrow(qc_data$fastqc$trimmed_r1)
} else {
	0L
}

trimmed_r2_n <- if (
	"fastqc" %in% names(qc_data) &&
	"trimmed_r2" %in% names(qc_data$fastqc)
) {
	nrow(qc_data$fastqc$trimmed_r2)
} else {
	0L
}

logr::log_print(
	paste("FastQC trimmed R1 rows after subsetting:", trimmed_r1_n),
	console = FALSE
)
logr::log_print(
	paste("FastQC trimmed R2 rows after subsetting:", trimmed_r2_n),
	console = FALSE
)

# FastQC recovery path: try generic subset, then FastQC-specific matching, then raw fallback.
if (
	(trimmed_r1_n == 0 || trimmed_r2_n == 0) &&
	!is.null(fastqc_pre_subset) &&
	"trimmed_r1" %in% names(fastqc_pre_subset) &&
	"trimmed_r2" %in% names(fastqc_pre_subset)
) {
	logr::log_print(
		"FastQC trimmed data were empty after generic subsetting; trying FastQC-specific recovery using Sample labels.",
		console = FALSE
	)
	qc_data$fastqc$trimmed_r1 <- recover_fastqc_subset(fastqc_pre_subset$trimmed_r1, qc_ids)
	qc_data$fastqc$trimmed_r2 <- recover_fastqc_subset(fastqc_pre_subset$trimmed_r2, qc_ids)
	trimmed_r1_n <- nrow(qc_data$fastqc$trimmed_r1)
	trimmed_r2_n <- nrow(qc_data$fastqc$trimmed_r2)
	logr::log_print(
		paste("FastQC trimmed R1 rows after recovery:", trimmed_r1_n),
		console = FALSE
	)
	logr::log_print(
		paste("FastQC trimmed R2 rows after recovery:", trimmed_r2_n),
		console = FALSE
	)
}

if (trimmed_r1_n == 0 || trimmed_r2_n == 0) {
	logr::log_print(
		"FastQC trimmed data still empty; reloading raw FastQC from MultiQC and using raw parsed trimmed R1/R2 for plotting.",
		console = FALSE
	)
	raw_qc <- load_paired_end_qc_data(data_dir = multiqc_dir)
	if ("fastqc" %in% names(raw_qc)) {
		fastqc_df <- raw_qc$fastqc
		sample_labels <- if ("Sample" %in% colnames(fastqc_df)) {
			as.character(fastqc_df$Sample)
		} else {
			rownames(fastqc_df)
		}
		sample_labels <- trimws(as.character(sample_labels))
		r1_mask <- grepl("\\.trimmed\\.R1$", sample_labels)
		r2_mask <- grepl("\\.trimmed\\.R2$", sample_labels)
		raw_r1 <- fastqc_df[r1_mask, , drop = FALSE]
		raw_r2 <- fastqc_df[r2_mask, , drop = FALSE]
		if (nrow(raw_r1) > 0) {
			rownames(raw_r1) <- make.unique(extract_fastq_id(sample_labels[r1_mask]))
		}
		if (nrow(raw_r2) > 0) {
			rownames(raw_r2) <- make.unique(extract_fastq_id(sample_labels[r2_mask]))
		}

		qc_data$fastqc$trimmed_r1 <- recover_fastqc_subset(raw_r1, qc_ids)
		qc_data$fastqc$trimmed_r2 <- recover_fastqc_subset(raw_r2, qc_ids)

		if (nrow(qc_data$fastqc$trimmed_r1) == 0 && nrow(raw_r1) > 0) {
			qc_data$fastqc$trimmed_r1 <- raw_r1
		}
		if (nrow(qc_data$fastqc$trimmed_r2) == 0 && nrow(raw_r2) > 0) {
			qc_data$fastqc$trimmed_r2 <- raw_r2
		}

		trimmed_r1_n <- nrow(qc_data$fastqc$trimmed_r1)
		trimmed_r2_n <- nrow(qc_data$fastqc$trimmed_r2)
		logr::log_print(
			paste("FastQC trimmed R1 rows after second recovery:", trimmed_r1_n),
			console = FALSE
		)
		logr::log_print(
			paste("FastQC trimmed R2 rows after second recovery:", trimmed_r2_n),
			console = FALSE
		)
	}
}

if (trimmed_r1_n == 0 || trimmed_r2_n == 0) {
	logr::log_print(
		"FastQC trimmed R1/R2 data are still empty; FastQC paired trimmed plots will be skipped.",
		console = FALSE
	)
}

logr::log_print(
	paste("Samples retained for QC:", length(qc_ids)),
	console = FALSE
)

if ("trimmomatic_dropped_pct" %in% group_vars) {
	trimmomatic_dropped_for_pca <- collect_metric({
		td <- qc_data$trimmomatic
		td <- td[qc_ids, , drop = FALSE]
		as_numeric <- suppressWarnings(as.numeric(td[, "dropped_pct"]))
		data.frame(trimmomatic_dropped_pct = as_numeric, row.names = qc_ids)
	}, "trimmomatic_dropped_pct_for_pca")
	if (!is.null(trimmomatic_dropped_for_pca)) {
		pheno_data$trimmomatic_dropped_pct <- trimmomatic_dropped_for_pca[rownames(pheno_data), 1]
		SummarizedExperiment::colData(dds)$trimmomatic_dropped_pct <- pheno_data$trimmomatic_dropped_pct
		SummarizedExperiment::colData(dds_vst)$trimmomatic_dropped_pct <- pheno_data$trimmomatic_dropped_pct
		logr::log_print(
			"Added trimmomatic_dropped_pct to phenotype data for PCA grouping.",
			console = FALSE
		)
	}
}

logr::sep("Plot QC summaries")

# Build plotting inputs from parsed FastQC data, with deterministic raw fallback.
fastqc_plot_data <- NULL
fastqc_plot_data <- tryCatch(
	{
		raw_fastqc <- load_paired_end_qc_data(data_dir = multiqc_dir)$fastqc
		parsed_fastqc <- parse_by_trim_status(
			raw_fastqc,
			paired_end = TRUE,
			r1_query = "(\\.R1|_R1)",
			r2_query = "(\\.R2|_R2)"
		)
		list(
			trimmed_r1 = parsed_fastqc$trimmed_r1,
			trimmed_r2 = parsed_fastqc$trimmed_r2
		)
	},
	error = function(e) {
		logr::log_print(
			paste0("Failed to build direct FastQC plotting data: ", e$message),
			console = FALSE
		)
		NULL
	}
)

fastqc_trimmed_r1_for_plot <- data.frame()
fastqc_trimmed_r2_for_plot <- data.frame()

if (
	!is.null(fastqc_plot_data) &&
	"trimmed_r1" %in% names(fastqc_plot_data) &&
	"trimmed_r2" %in% names(fastqc_plot_data) &&
	is.data.frame(fastqc_plot_data$trimmed_r1) &&
	is.data.frame(fastqc_plot_data$trimmed_r2)
) {
	fastqc_trimmed_r1_for_plot <- fastqc_plot_data$trimmed_r1
	fastqc_trimmed_r2_for_plot <- fastqc_plot_data$trimmed_r2
}

# Deterministic fallback: extract paired trimmed rows directly from raw fastqc.
if (nrow(fastqc_trimmed_r1_for_plot) == 0 || nrow(fastqc_trimmed_r2_for_plot) == 0) {
	logr::log_print(
		"Direct parse returned empty FastQC trimmed tables for plotting; applying raw suffix-based fallback.",
		console = FALSE
	)
	raw_fastqc_df <- load_paired_end_qc_data(data_dir = multiqc_dir)$fastqc
	raw_labels <- if ("Sample" %in% colnames(raw_fastqc_df)) {
		as.character(raw_fastqc_df$Sample)
	} else {
		rownames(raw_fastqc_df)
	}
	raw_labels <- trimws(as.character(raw_labels))
	r1_mask <- grepl("\\.trimmed\\.R1$", raw_labels)
	r2_mask <- grepl("\\.trimmed\\.R2$", raw_labels)
	fastqc_trimmed_r1_for_plot <- raw_fastqc_df[r1_mask, , drop = FALSE]
	fastqc_trimmed_r2_for_plot <- raw_fastqc_df[r2_mask, , drop = FALSE]
}

logr::log_print(
	paste("FastQC paired plot rows (R1):", nrow(fastqc_trimmed_r1_for_plot)),
	console = FALSE
)
logr::log_print(
	paste("FastQC paired plot rows (R2):", nrow(fastqc_trimmed_r2_for_plot)),
	console = FALSE
)

with_plot_guard({
	p3 <- plot_seq_depth(fastqc_trimmed_r1_for_plot, sort = TRUE) +
		ggplot2::ggtitle("Post-Trimmomatic paired R1 reads")
	p4 <- plot_seq_depth(fastqc_trimmed_r2_for_plot, sort = TRUE) +
		ggplot2::ggtitle("Post-Trimmomatic paired R2 reads")
	h3 <- plot_seq_depth_hist(fastqc_trimmed_r1_for_plot) +
		ggplot2::ggtitle("Post-Trimmomatic paired R1 reads")
	h4 <- plot_seq_depth_hist(fastqc_trimmed_r2_for_plot) +
		ggplot2::ggtitle("Post-Trimmomatic paired R2 reads")
	save_plot((p3 + h3) / (p4 + h4), "fastqc_seq_depth_posttrimmomatic_paired.png", 12.5, 8)
}, "seq depth")

with_plot_guard({
	p3 <- plot_unique_read_pct(
		fastqc_trimmed_r1_for_plot, sort = TRUE, fill = "red4"
	) + ggplot2::ggtitle("Post-Trimmomatic paired R1 reads")
	p4 <- plot_unique_read_pct(
		fastqc_trimmed_r2_for_plot, sort = TRUE, fill = "red4"
	) + ggplot2::ggtitle("Post-Trimmomatic paired R2 reads")
	save_plot(p3 + p4, "fastqc_unique_pct_posttrimmomatic_paired.png", 12.5, 4.5)
}, "unique read percent")

with_plot_guard({
	p <- plot_phred_per_bp(
		qc_data$phred_bp[c("trimmed_r1", "trimmed_r2")],
		labels = c("R1", "R2"),
		line_colors = c("goldenrod2", "steelblue4"),
		alpha = 0.5
	) + ggplot2::ggtitle("Post-Trimmomatic paired reads")
	save_plot(p, "fastqc_phred_bp_posttrimmomatic_paired.png", 9, 4)
}, "phred per bp")

with_plot_guard({
	p <- plot_gc_content(
		qc_data$gc_content[c("trimmed_r1", "trimmed_r2")],
		labels = c("R1", "R2"),
		line_colors = c("goldenrod2", "steelblue4"),
		alpha = 0.5
	) + ggplot2::ggtitle("Post-Trimmomatic paired reads")
	save_plot(p, "fastqc_gc_content_posttrimmomatic_paired.png", 7, 4)
}, "gc content")

with_plot_guard({
	p_trim <- plot_trimmomatic_paired(
		data = qc_data$trimmomatic,
		binsize = c(2.5, 0.25)
	)
	save_plot(p_trim$excluded + p_trim$retained, "trimmomatic_stats.png", 9, 4)
}, "trimmomatic")

with_plot_guard({
	p <- plot_salmon_stats(qc_data$salmon)
	save_plot(p, "salmon_input_vs_mapped.png", 5, 4)
}, "salmon scatter")

with_plot_guard({
	p <- plot_hisat2_stats(qc_data$hisat2)
	save_plot(p, "hisat2_mapping_stats.png", 6, 5)
}, "hisat2 scatter")

with_plot_guard({
	p <- plot_hisat2_vs_salmon(qc_data$hisat2, qc_data$salmon)
	save_plot(p, "salmon_vs_hisat2_mapping_rate.png", 5, 5)
}, "salmon vs hisat2")

with_plot_guard({
	p <- plot_mapping_categories(
		qc_data$rseqc_alignment_category,
		sort = TRUE,
		consolidate = TRUE
	)
	save_plot(p, "rseqc_read_distribution_consolidated.png", 14, 7)
}, "mapping categories")

with_plot_guard({
	if (rin_col %in% colnames(pheno_data)) {
		p <- plot_rin(
			data = pheno_data[, rin_col, drop = FALSE],
			return_data = FALSE,
			colors = "gray30",
			box_fill = "goldenrod",
			jitter_alpha = 0.5
		)
		save_plot(p$hist / p$boxplot, "rin.png", 6, 6)
	} else {
		logr::log_print(
			paste0("RIN column '", rin_col, "' not found. Skipping RIN plot."),
			console = FALSE
		)
	}
}, "rin")

logr::log_print("Starting streamed annotation ID extraction.", console = FALSE)
mitochondrial_ids <- get_annotation_gene_ids(annotation_gtf, seqnames = c("chrM", "MT", "M"))
ribo_ids <- get_annotation_gene_ids(annotation_gtf, gene_types = c("rRNA"))
logr::log_print(
	paste0(
		"Resolved feature IDs - mitochondrial: ", length(mitochondrial_ids),
		"; ribosomal: ", length(ribo_ids)
	),
	console = FALSE
)

mitochondrial_mapping_rate <- collect_metric({
	out <- compute_feature_fraction(normalized_counts, mitochondrial_ids)
	out <- out[qc_ids, "values", drop = FALSE]
	colnames(out) <- "mitochondrial_mapping_rate"
	out
}, "mitochondrial_mapping_rate")
logr::log_print("Computed mitochondrial mapping rate.", console = FALSE)

ribo_rna_mapping_rate <- collect_metric({
	out <- compute_feature_fraction(normalized_counts, ribo_ids)
	out <- out[qc_ids, "values", drop = FALSE]
	colnames(out) <- "ribo_rna_mapping_rate"
	out
}, "ribo_rna_mapping_rate")
logr::log_print("Computed ribosomal RNA mapping rate.", console = FALSE)

with_plot_guard({
	p <- plot_fraction_summary(
		mitochondrial_mapping_rate,
		"Mitochondrial RNA"
	)
	save_plot(p$hist / p$boxplot, "mitochondrial_mapping_rate.png", 6, 6)
}, "mitochondrial")
logr::log_print("Completed mitochondrial plot block.", console = FALSE)

if (!is.null(mitochondrial_mapping_rate)) {
	pheno_data$mitochondrial_mapping_rate <- mitochondrial_mapping_rate[rownames(pheno_data), 1]
	SummarizedExperiment::colData(dds)$mitochondrial_mapping_rate <- pheno_data$mitochondrial_mapping_rate
	SummarizedExperiment::colData(dds_vst)$mitochondrial_mapping_rate <- pheno_data$mitochondrial_mapping_rate
}

with_plot_guard({
	p <- plot_fraction_summary(
		ribo_rna_mapping_rate,
		"Ribosomal RNA"
	)
	save_plot(p$hist / p$boxplot, "ribosomal_rna_mapping_rate.png", 6, 6)
}, "ribosomal")
logr::log_print("Completed ribosomal plot block.", console = FALSE)

with_plot_guard({
	p <- plot_shannon_index(
		data = DESeq2::counts(dds, normalized = TRUE),
		min_value = 10,
		colors = "gray30"
	)
	save_plot(p$hist / p$boxplot, "shannon_diversity.png", 6, 6)
}, "shannon")

with_plot_guard({
	if (sex_col %in% colnames(pheno_data)) {
		chr_y_ids <- get_annotation_gene_ids(
			annotation_gtf,
			seqnames = c("chrY", "Y"),
			exclude_par = TRUE
		)
		chr_y_ids <- intersect(chr_y_ids, rownames(normalized_counts))

		if (length(chr_y_ids) == 0) {
			logr::log_print(
				"No chrY genes found in expression matrix after annotation overlap. Skipping chrY-by-sex plot.",
				console = FALSE
			)
			return(NULL)
		}

		chr_y_mean <- colMeans(normalized_counts[chr_y_ids, , drop = FALSE], na.rm = TRUE)
		plot_df <- data.frame(
			sample_id = names(chr_y_mean),
			chr_y_mean_counts = as.numeric(chr_y_mean),
			group = as.character(pheno_data[names(chr_y_mean), sex_col]),
			stringsAsFactors = FALSE
		)

		plot_df$group <- as.factor(plot_df$group)
		p <- ggplot2::ggplot(
			plot_df,
			ggplot2::aes(x = group, y = chr_y_mean_counts, fill = group)
		) +
			ggplot2::geom_boxplot(outlier.alpha = 0.2) +
			ggplot2::geom_jitter(width = 0.15, alpha = 0.75, size = 2, color = "gray20") +
			ggplot2::labs(
				title = "chrY Mean Normalized Counts by Sex",
				x = sex_col,
				y = "Mean normalized chrY counts",
				fill = sex_col
			) +
			ggplot2::theme_bw() +
			ggplot2::coord_flip()

		save_plot(p, "chrY_mean_counts_by_sex.png", 8, 5)
	} else {
		logr::log_print(
			paste0("Sex column '", sex_col, "' not found. Skipping chrY-by-sex plot."),
			console = FALSE
		)
	}
}, "chrY by sex")

# PCA is optional and runs only when user-provided grouping variables are available.
if (length(group_vars) == 0) {
	logr::log_print("Skipping PCA plot block because --group_vars was not provided.", console = FALSE)
} else {
	with_plot_guard({
		p_patch <- build_pca_patch()
		if (!is.null(p_patch)) {
			save_plot(p_patch, "pca_plots_pc1_pc2.png", 16, 14)
		}
	}, "pca")
	logr::log_print("Completed PCA plot block.", console = FALSE)
}

# Recompute metrics from consistently aligned QC data and write the sample table.
logr::sep("Build QC metrics table")

# Re-load raw QC where needed to compute metric tables from consistent trimmed subsets.
raw_qc_for_metrics <- load_paired_end_qc_data(data_dir = multiqc_dir)
phred_trimmed_for_metrics <- if ("phred_seq" %in% names(raw_qc_for_metrics)) {
	extract_trimmed_pairs(raw_qc_for_metrics$phred_seq)
} else {
	list(trimmed_r1 = data.frame(), trimmed_r2 = data.frame())
}
gc_trimmed_for_metrics <- if ("gc_content" %in% names(raw_qc_for_metrics)) {
	extract_trimmed_pairs(raw_qc_for_metrics$gc_content)
} else {
	list(trimmed_r1 = data.frame(), trimmed_r2 = data.frame())
}

logr::log_print(
	paste0(
		"Metric source rows - phred trimmed R1/R2: ",
		nrow(phred_trimmed_for_metrics$trimmed_r1), "/", nrow(phred_trimmed_for_metrics$trimmed_r2),
		"; gc trimmed R1/R2: ",
		nrow(gc_trimmed_for_metrics$trimmed_r1), "/", nrow(gc_trimmed_for_metrics$trimmed_r2)
	),
	console = FALSE
)

qc_metrics_list <- list()

# Collect each metric independently so one missing modality does not collapse the table.
qc_metrics_list$trimmomatic_dropped_pct <- collect_metric({
	td <- qc_data$trimmomatic
	td <- td[qc_ids, , drop = FALSE]
	out <- td[, "dropped_pct", drop = FALSE]
	colnames(out) <- "trimmomatic_dropped_pct"
	out
}, "trimmomatic_dropped_pct")

qc_metrics_list$mean_phred_r1 <- collect_metric({
	out <- plot_phred_mean(
		data = phred_trimmed_for_metrics$trimmed_r1,
		return_data = TRUE
	)
	out <- align_metric_output(out, qc_ids, value_col = "values")
	colnames(out) <- "mean_phred_r1"
	out
}, "mean_phred_r1")

qc_metrics_list$mean_phred_r2 <- collect_metric({
	out <- plot_phred_mean(
		data = phred_trimmed_for_metrics$trimmed_r2,
		return_data = TRUE
	)
	out <- align_metric_output(out, qc_ids, value_col = "values")
	colnames(out) <- "mean_phred_r2"
	out
}, "mean_phred_r2")

qc_metrics_list$mean_pct_gc_r1 <- collect_metric({
	out <- plot_gc_mean(
		data = gc_trimmed_for_metrics$trimmed_r1,
		return_data = TRUE
	)
	out <- align_metric_output(out, qc_ids, value_col = "values")
	colnames(out) <- "mean_pct_gc_r1"
	out
}, "mean_pct_gc_r1")

qc_metrics_list$mean_pct_gc_r2 <- collect_metric({
	out <- plot_gc_mean(
		data = gc_trimmed_for_metrics$trimmed_r2,
		return_data = TRUE
	)
	out <- align_metric_output(out, qc_ids, value_col = "values")
	colnames(out) <- "mean_pct_gc_r2"
	out
}, "mean_pct_gc_r2")

qc_metrics_list$pct_unique_r1 <- collect_metric({
	out <- plot_unique_read_pct(
		data = fastqc_trimmed_r1_for_plot,
		sort = FALSE,
		return_data = TRUE
	)
	out <- align_metric_output(out, qc_ids, value_col = "values")
	colnames(out) <- "pct_unique_r1"
	out
}, "pct_unique_r1")

qc_metrics_list$pct_unique_r2 <- collect_metric({
	out <- plot_unique_read_pct(
		data = fastqc_trimmed_r2_for_plot,
		sort = FALSE,
		return_data = TRUE
	)
	out <- align_metric_output(out, qc_ids, value_col = "values")
	colnames(out) <- "pct_unique_r2"
	out
}, "pct_unique_r2")

qc_metrics_list$salmon_mapping_pct <- collect_metric({
	out <- plot_salmon_mapping_pct(data = qc_data$salmon, return_data = TRUE)
	out <- out[qc_ids, "values", drop = FALSE]
	colnames(out) <- "salmon_mapping_pct"
	out
}, "salmon_mapping_pct")

qc_metrics_list$hisat2_mapping_pct <- collect_metric({
	out <- extract_hisat2_mapping_pct(qc_data$hisat2)
	out <- subset_qc_df(out, qc_ids)
	out <- out[qc_ids, "values", drop = FALSE]
	colnames(out) <- "hisat2_mapping_pct"
	out
}, "hisat2_mapping_pct")

qc_metrics_list$effective_seq_depth <- collect_metric({
	out <- plot_salmon_mapped_reads(data = qc_data$salmon, return_data = TRUE)
	out <- out[qc_ids, "values", drop = FALSE]
	colnames(out) <- "effective_seq_depth"
	out
}, "effective_seq_depth")

qc_metrics_list$mapping_categories <- collect_metric({
	map_data <- plot_mapping_categories(
		qc_data$rseqc_alignment_category,
		sort = TRUE,
		consolidate = TRUE,
		return_data = TRUE
	)
	map_data <- subset_qc_df(map_data, qc_ids)
	out <- data.frame(
		intergenic_mapping_pct = map_data[qc_ids, "Intergenic", drop = TRUE],
		intron_mapping_pct = map_data[qc_ids, "Intronic", drop = TRUE],
		exon_mapping_pct = map_data[qc_ids, "Exonic", drop = TRUE],
		row.names = qc_ids,
		stringsAsFactors = FALSE
	)
	out
}, "mapping_categories")

qc_metrics_list$gene_mapping_pct <- collect_metric({
	map_data <- plot_mapping_categories(
		qc_data$rseqc_alignment_category,
		sort = TRUE,
		consolidate = TRUE,
		return_data = TRUE
	)
	map_data <- subset_qc_df(map_data, qc_ids)
	out <- plot_gene_mapping_rate(
		data = map_data[, c("Exonic", "Intronic"), drop = FALSE],
		group = NULL,
		return_data = TRUE
	)
	out <- out[qc_ids, "values", drop = FALSE]
	colnames(out) <- "gene_mapping_pct"
	out
}, "gene_mapping_pct")

qc_metrics_list$dna_contamination_ratio <- collect_metric({
	map_data <- plot_mapping_categories(
		qc_data$rseqc_alignment_category,
		sort = TRUE,
		consolidate = TRUE,
		return_data = TRUE
	)
	map_data <- subset_qc_df(map_data, qc_ids)
	out <- plot_dna_contamination_ratio(
		data = map_data[, c("Intergenic", "Intronic"), drop = FALSE],
		group = NULL,
		return_data = TRUE
	)
	out <- out[qc_ids, "values", drop = FALSE]
	colnames(out) <- "dna_contamination_ratio"
	out
}, "dna_contamination_ratio")

if (rin_col %in% colnames(pheno_data)) {
	rin_df <- pheno_data[qc_ids, rin_col, drop = FALSE]
	colnames(rin_df) <- "rin"
	qc_metrics_list$rin <- rin_df
}

qc_metrics_list$mito_rna_pct <- collect_metric({
	out <- mitochondrial_mapping_rate[qc_ids, , drop = FALSE]
	colnames(out) <- "mito_rna_pct"
	out
}, "mito_rna_pct")

qc_metrics_list$ribo_rna_pct <- collect_metric({
	out <- ribo_rna_mapping_rate[qc_ids, , drop = FALSE]
	colnames(out) <- "ribo_rna_pct"
	out
}, "ribo_rna_pct")

qc_metrics_list$shannon_index <- collect_metric({
	out <- plot_shannon_index(
		data = DESeq2::counts(dds, normalized = TRUE),
		min_value = 10,
		return = TRUE
	)
	out <- out[qc_ids, "values", drop = FALSE]
	colnames(out) <- "shannon_index"
	out
}, "shannon_index")

if (sex_col %in% colnames(pheno_data)) {
	qc_metrics_list$chr_y_mean_counts <- collect_metric({
		dds_tmp <- dds
		SummarizedExperiment::assay(dds_tmp) <- DESeq2::counts(dds, normalized = TRUE)
		chr_y_ids <- get_annotation_gene_ids(
			annotation_gtf,
			seqnames = c("chrY", "Y"),
			exclude_par = TRUE
		)
		chr_y_ids <- intersect(chr_y_ids, rownames(dds_vst))
		out <- plot_partitioned_mean_expression(
			dds_tmp,
			group_var = sex_col,
			feature_ids = chr_y_ids,
			invert_cols = TRUE,
			return_data = TRUE
		)
		out <- out[qc_ids, "values", drop = FALSE]
		colnames(out) <- "chr_y_mean_counts"
		out
	}, "chr_y_mean_counts")

	qc_metrics_list$chr_y_pc1 <- collect_metric({
		chr_y_ids <- get_annotation_gene_ids(
			annotation_gtf,
			seqnames = c("chrY", "Y"),
			exclude_par = TRUE
		)
		chr_y_ids <- intersect(chr_y_ids, rownames(dds_vst))
		out <- plot_partitioned_pc(
			dds_vst,
			pc = 1,
			group_var = sex_col,
			center = TRUE,
			scale = FALSE,
			feature_ids = chr_y_ids,
			return_data = TRUE
		)
		out <- out[qc_ids, "values", drop = FALSE]
		colnames(out) <- "chr_y_pc1"
		out
	}, "chr_y_pc1")
} else {
	logr::log_print(
		paste0("Sex column '", sex_col, "' not found. Skipping chrY-based metrics."),
		console = FALSE
	)
}

qc_metrics_list <- qc_metrics_list[!vapply(qc_metrics_list, is.null, logical(1))]

if (length(qc_metrics_list) == 0) {
	stop("No QC metrics could be generated.")
}

qc_metrics <- do.call(cbind, qc_metrics_list)
qc_metrics <- tibble::rownames_to_column(as.data.frame(qc_metrics), var = "sample_id")

# Join computed metrics back onto phenotype for one analysis-ready sample table.
pheno_out <- pheno_data
pheno_out$sample_id <- rownames(pheno_out)

# Avoid duplicate mitochondrial-rate representations in the final table.
# Keep mito_rna_pct from computed QC metrics and drop the legacy phenotype copy.
if (
	"mito_rna_pct" %in% colnames(qc_metrics) &&
	"mitochondrial_mapping_rate" %in% colnames(pheno_out)
) {
	pheno_out <- pheno_out[, setdiff(colnames(pheno_out), "mitochondrial_mapping_rate"), drop = FALSE]
}

duplicate_metric_cols <- intersect(
	setdiff(colnames(qc_metrics), "sample_id"),
	colnames(pheno_out)
)
if (length(duplicate_metric_cols) > 0) {
	pheno_out <- pheno_out[, setdiff(colnames(pheno_out), duplicate_metric_cols), drop = FALSE]
}
rnaseq_pheno_qc <- dplyr::left_join(pheno_out, qc_metrics, by = "sample_id")

qc_out_file <- file.path(table_dir, paste0(run_name, "_bulk_rnaseq_qc_metrics.tsv"))
write.table(
	rnaseq_pheno_qc,
	file = qc_out_file,
	sep = "\t",
	row.names = FALSE,
	col.names = TRUE,
	quote = FALSE
)

logr::log_print("QC metrics table written to:", console = FALSE, blank_after = FALSE)
logr::log_print(qc_out_file, console = FALSE)

sample_ids <- if ("sample_id" %in% colnames(rnaseq_pheno_qc)) {
	as.character(rnaseq_pheno_qc$sample_id)
} else {
	as.character(seq_len(nrow(rnaseq_pheno_qc)))
}

rin_values <- get_metric_numeric(rnaseq_pheno_qc, "rin", fallback_cols = c(rin_col))
effective_seq_depth <- get_metric_numeric(rnaseq_pheno_qc, "effective_seq_depth")
trimmomatic_dropped_pct <- get_metric_numeric(rnaseq_pheno_qc, "trimmomatic_dropped_pct")
retained_reads_pct <- 100 - trimmomatic_dropped_pct
mean_pct_gc_r1 <- get_metric_numeric(rnaseq_pheno_qc, "mean_pct_gc_r1")
mean_pct_gc_r2 <- get_metric_numeric(rnaseq_pheno_qc, "mean_pct_gc_r2")
mean_read_gc_pct <- rowMeans(cbind(mean_pct_gc_r1, mean_pct_gc_r2), na.rm = TRUE)
mean_read_gc_pct[is.nan(mean_read_gc_pct)] <- NA_real_
salmon_mapping_pct <- get_metric_numeric(rnaseq_pheno_qc, "salmon_mapping_pct")
gene_mapping_pct <- get_metric_numeric(rnaseq_pheno_qc, "gene_mapping_pct")
intergenic_mapping_pct <- get_metric_numeric(
	rnaseq_pheno_qc,
	"intergenic_mapping_pct",
	fallback_cols = c("mapping_categories.intergenic_mapping_pct")
)
intergenic_genic_ratio <- intergenic_mapping_pct / gene_mapping_pct
intergenic_genic_ratio[!is.finite(intergenic_genic_ratio)] <- NA_real_
shannon_index <- get_metric_numeric(rnaseq_pheno_qc, "shannon_index")
transcriptome_mapping_pct <- salmon_mapping_pct
mito_rna_pct <- get_metric_numeric(rnaseq_pheno_qc, "mito_rna_pct")
ribo_rna_pct <- get_metric_numeric(rnaseq_pheno_qc, "ribo_rna_pct")

# Derive Shannon lower bound using Tukey-style outlier threshold on the cohort.
shannon_non_na <- shannon_index[!is.na(shannon_index)]
if (length(shannon_non_na) > 0) {
	shannon_q1 <- as.numeric(stats::quantile(shannon_non_na, probs = 0.25, names = FALSE, na.rm = TRUE))
	shannon_iqr <- stats::IQR(shannon_non_na, na.rm = TRUE)
	shannon_cutoff <- shannon_q1 - (1.5 * shannon_iqr)
} else {
	shannon_cutoff <- NA_real_
}
logr::log_print(
	paste0("Shannon index IQR-based cutoff (Q1 - 1.5*IQR): ", round(shannon_cutoff, 4)),
	console = FALSE
)

pass_rin <- !is.na(rin_values) & rin_values > 5
pass_effective_depth <- !is.na(effective_seq_depth) & effective_seq_depth > 10
pass_retained_reads <- !is.na(retained_reads_pct) & retained_reads_pct > 60
pass_mean_gc <- !is.na(mean_read_gc_pct) & mean_read_gc_pct >= 35 & mean_read_gc_pct <= 65
pass_salmon_mapping <- !is.na(salmon_mapping_pct) & salmon_mapping_pct > 30
pass_gene_mapping <- !is.na(gene_mapping_pct) & gene_mapping_pct > 80
pass_intergenic_genic_ratio <- !is.na(intergenic_genic_ratio) & intergenic_genic_ratio < 0.9
pass_shannon_or_transcriptome <-
	((!is.na(shannon_cutoff)) & !is.na(shannon_index) & shannon_index > shannon_cutoff) |
	(!is.na(transcriptome_mapping_pct) & transcriptome_mapping_pct > 50)
pass_mito <- !is.na(mito_rna_pct) & mito_rna_pct < 50
pass_ribo <- !is.na(ribo_rna_pct) & ribo_rna_pct < 1

# Centralized threshold definitions drive both counts and failed-sample reporting.
threshold_defs <- list(
	list(
		metric = "rin_gt5",
		rule = paste0(rin_col, " > 5"),
		pass = pass_rin
	),
	list(
		metric = "effective_seq_depth_gt10m",
		rule = "Effective sequencing depth > 10 million reads",
		pass = pass_effective_depth
	),
	list(
		metric = "retained_reads_pct_gt60",
		rule = "Post-Trimmomatic retained reads percentage > 60%",
		pass = pass_retained_reads
	),
	list(
		metric = "mean_read_gc_pct_35_to_65",
		rule = "Mean read GC content between 35% and 65%",
		pass = pass_mean_gc
	),
	list(
		metric = "salmon_mapping_pct_gt30",
		rule = "Salmon mapping percentage > 30%",
		pass = pass_salmon_mapping
	),
	list(
		metric = "gene_mapping_pct_gt80",
		rule = "Gene mapping percentage (intronic + exonic) > 80%",
		pass = pass_gene_mapping
	),
	list(
		metric = "intergenic_genic_ratio_lt0.9",
		rule = "Intergenic/genic mapping ratio < 0.9",
		pass = pass_intergenic_genic_ratio
	),
	list(
		metric = "shannon_or_transcriptome_mapping",
		rule = "Shannon index > IQR cutoff OR transcriptome mapping percentage > 50%",
		pass = pass_shannon_or_transcriptome
	),
	list(
		metric = "mitochondrial_mapping_pct_lt50",
		rule = "Mitochondrial mapping percentage < 50%",
		pass = pass_mito
	),
	list(
		metric = "ribosomal_rna_mapping_pct_lt1",
		rule = "Ribosomal RNA mapping percentage < 1%",
		pass = pass_ribo
	)
)

summary_rows <- lapply(threshold_defs, function(td) {
	pass_vec <- td$pass
	n_pass <- sum(pass_vec, na.rm = TRUE)
	n_fail <- sum(!pass_vec, na.rm = TRUE)
	data.frame(
		metric = td$metric,
		rule = td$rule,
		n_pass = n_pass,
		n_fail = n_fail,
		total_samples = nrow(rnaseq_pheno_qc),
		stringsAsFactors = FALSE
	)
})
summary_df <- do.call(rbind, summary_rows)

failed_rows <- lapply(threshold_defs, function(td) {
	pass_vec <- td$pass
	fail_ids <- sample_ids[!pass_vec]
	fail_ids <- fail_ids[!is.na(fail_ids) & nzchar(fail_ids)]
	data.frame(
		metric = td$metric,
		rule = td$rule,
		n_failed = length(fail_ids),
		failed_samples = if (length(fail_ids) == 0) "None" else paste(fail_ids, collapse = ", "),
		stringsAsFactors = FALSE
	)
})
failed_samples_df <- do.call(rbind, failed_rows)

summary_out_file <- file.path(
	table_dir,
	paste0(run_name, "_bulk_rnaseq_qc_threshold_summary.tsv")
)
write.table(
	summary_df,
	file = summary_out_file,
	sep = "\t",
	row.names = FALSE,
	col.names = TRUE,
	quote = FALSE
)

logr::log_print("Threshold summary written to:", console = FALSE, blank_after = FALSE)
logr::log_print(summary_out_file, console = FALSE)

if (length(group_vars) == 0) {
	logr::log_print("Skipping QC-pass-only PCA because --group_vars was not provided.", console = FALSE)
} else {
	pass_all_thresholds <- Reduce(`&`, lapply(threshold_defs, function(td) {
		pass_vec <- td$pass
		pass_vec[is.na(pass_vec)] <- FALSE
		pass_vec
	}))
	pass_sample_ids <- sample_ids[pass_all_thresholds]

	with_plot_guard({
		p_pass_patch <- build_pca_patch(sample_ids_subset = pass_sample_ids)
		if (!is.null(p_pass_patch)) {
			save_plot(p_pass_patch, "pca_plots_pc1_pc2_qc_pass_only.png", 16, 14)
			logr::log_print(
				paste0("Saved QC-pass-only PCA plot for ", length(pass_sample_ids), " samples."),
				console = FALSE
			)
		}
	}, "pca qc-pass-only")
}

# Build linked HTML and GitHub-flavored Markdown reports from the same outputs.
logr::sep("Build HTML report")

plot_files <- sort(list.files(plot_dir, pattern = "\\.png$", full.names = FALSE))

plot_cards <- if (length(plot_files) == 0) {
	"<p>No plot images were found.</p>"
} else {
	paste0(
		vapply(
			plot_files,
			function(pf) {
				plot_title <- sub("\\.png$", "", pf)
				if (startsWith(plot_title, paste0(run_name, "_"))) {
					plot_title <- substring(plot_title, nchar(run_name) + 2)
				}
				img_src <- file.path("plots", pf)
				paste0(
					"<div class='plot-card'>",
					"<h3>", html_escape(plot_title), "</h3>",
					"<img src='", html_escape(img_src), "' alt='", html_escape(plot_title), "'>",
					"</div>"
				)
			},
			character(1)
		),
		collapse = "\n"
	)
}

threshold_html <- df_to_html_table(summary_df, max_rows = NULL)
failed_samples_html <- df_to_html_table(failed_samples_df, max_rows = NULL)

report_file <- file.path(out_dir, paste0(run_name, "_qc_summary.html"))

# Build a self-contained report that links tables/logs and embeds all generated PNGs.
html_lines <- c(
	"<!doctype html>",
	"<html lang='en'>",
	"<head>",
	"<meta charset='utf-8'>",
	"<meta name='viewport' content='width=device-width, initial-scale=1'>",
	paste0("<title>", html_escape(run_name), " QC Summary</title>"),
	"<style>",
	":root { --bg: #f6f7fb; --panel: #ffffff; --ink: #1f2937; --muted: #4b5563; --line: #d1d5db; --accent: #0f766e; }",
	"body { margin: 0; background: linear-gradient(140deg, #f8fafc, #eef2ff); color: var(--ink); font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; }",
	".wrap { max-width: 1200px; margin: 0 auto; padding: 24px; }",
	".hero { background: var(--panel); border: 1px solid var(--line); border-radius: 12px; padding: 18px 20px; box-shadow: 0 8px 24px rgba(15, 23, 42, 0.08); }",
	"h1 { margin: 0 0 8px 0; font-size: 28px; }",
	"h2 { margin: 26px 0 10px 0; font-size: 22px; }",
	"h3 { margin: 0 0 8px 0; font-size: 16px; color: var(--muted); }",
	"p.meta { margin: 6px 0; color: var(--muted); }",
	".links a { color: var(--accent); text-decoration: none; margin-right: 14px; }",
	".links a:hover { text-decoration: underline; }",
	".qc-table { width: 100%; border-collapse: collapse; background: var(--panel); border: 1px solid var(--line); border-radius: 10px; overflow: hidden; }",
	".qc-table th, .qc-table td { border-bottom: 1px solid #e5e7eb; padding: 8px 10px; text-align: left; font-size: 13px; }",
	".qc-table th { background: #f9fafb; position: sticky; top: 0; }",
	".table-wrap { overflow-x: auto; border-radius: 10px; box-shadow: 0 6px 18px rgba(15, 23, 42, 0.06); }",
	".plot-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(360px, 1fr)); gap: 14px; }",
	".plot-card { background: var(--panel); border: 1px solid var(--line); border-radius: 12px; padding: 10px; box-shadow: 0 6px 20px rgba(15, 23, 42, 0.08); }",
	".plot-card img { width: 100%; height: auto; border-radius: 8px; display: block; }",
	"@media (max-width: 700px) { .wrap { padding: 14px; } .plot-grid { grid-template-columns: 1fr; } }",
	"</style>",
	"</head>",
	"<body>",
	"<div class='wrap'>",
	"<div class='hero'>",
	paste0("<h1>", html_escape(run_name), " - Bulk RNA-seq QC Summary</h1>"),
	paste0("<p class='meta'><strong>Generated:</strong> ", html_escape(as.character(Sys.time())), "</p>"),
	paste0("<p class='meta'><strong>Total samples:</strong> ", nrow(rnaseq_pheno_qc), "</p>"),
	paste0("<p class='meta'><strong>Plots found:</strong> ", length(plot_files), "</p>"),
	"<div class='links'>",
	paste0("<a href='", file.path("tables", basename(qc_out_file)), "'>QC metrics TSV</a>"),
	paste0("<a href='", file.path("tables", basename(summary_out_file)), "'>Threshold summary TSV</a>"),
	paste0("<a href='", basename(log_file), "'>Log file</a>"),
	"</div>",
	"</div>",
	"<h2>Threshold Summary</h2>",
	"<div class='table-wrap'>",
	threshold_html,
	"</div>",
	"<h2>Samples That Did Not Pass Each Filter</h2>",
	"<div class='table-wrap'>",
	failed_samples_html,
	"</div>",
	"<h2>QC Plots</h2>",
	"<div class='plot-grid'>",
	plot_cards,
	"</div>",
	"</div>",
	"</body>",
	"</html>"
)

writeLines(html_lines, con = report_file)
logr::log_print("HTML report written to:", console = FALSE, blank_after = FALSE)
logr::log_print(report_file, console = FALSE)

# Render a GitHub-flavored Markdown report using the same QC outputs.
markdown_plots <- if (length(plot_files) == 0) {
	"_No plot images were found._"
} else {
	paste0(
		vapply(
			plot_files,
			function(pf) {
				plot_title <- sub("\\.png$", "", pf)
				if (startsWith(plot_title, paste0(run_name, "_"))) {
					plot_title <- substring(plot_title, nchar(run_name) + 2)
				}
				paste0(
					"### ", markdown_escape(plot_title), "\n\n",
					"![", markdown_escape(plot_title), "](", file.path("plots", pf), ")"
				)
			},
			character(1)
		),
		collapse = "\n"
	)
}

markdown_report_file <- file.path(out_dir, paste0(run_name, "_qc_summary.md"))
markdown_lines <- c(
	paste0("# ", markdown_escape(run_name), " - Bulk RNA-seq QC Summary"),
	"",
	paste0("**Generated:** ", markdown_escape(as.character(Sys.time()))),
	paste0("**Total samples:** ", nrow(rnaseq_pheno_qc)),
	paste0("**Plots found:** ", length(plot_files)),
	"",
	"## Output Files",
	"",
	paste0("- [QC metrics TSV](tables/", basename(qc_out_file), ")"),
	paste0("- [Threshold summary TSV](tables/", basename(summary_out_file), ")"),
	paste0("- [Log file](", basename(log_file), ")"),
	"",
	"## Threshold Summary",
	"",
	df_to_markdown_table(summary_df),
	"",
	"## Samples That Did Not Pass Each Filter",
	"",
	df_to_markdown_table(failed_samples_df),
	"",
	"## QC Plots",
	"",
	markdown_plots,
	""
)

writeLines(markdown_lines, con = markdown_report_file)
logr::log_print("Markdown report written to:", console = FALSE, blank_after = FALSE)
logr::log_print(markdown_report_file, console = FALSE)

logr::sep("QC pipeline complete")
logr::log_print("Bulk RNA-seq QC finished successfully.", console = FALSE)
